In [19]:
import numpy as np
import random
from munkres import Munkres, print_matrix

numberObjectif=2 #nombre d'objectifs
#lecture
with open('LAP-8-2objSOL.dat') as f:
    size = int(f.readline()) #taille de la matrice
    alldata = [] #toute les données des objectifs
    for k in range(numberObjectif):
        data = []
        for i in range(size):
            data.append(f.readline())
        for i in range(len(data)):
            data[i]=data[i].strip('\n').split()
            for j in range(len(data[i])):
                data[i][j]=int(data[i][j])
        alldata.append(data)
matrix = alldata[1]
print_matrix(alldata[0])
m = Munkres()
indexes = m.compute(alldata[0])
print(indexes)
test = np.zeros((8,8))
for i in indexes:
    test[i[0],i[1]]=1
print(test)
print ('coût=', sum([matrix[i[0]][i[1]] for i in indexes]))

[ 1,  6,  5,  2,  5, 10,  3,  6]
[ 7,  8,  9,  2,  7,  2,  9,  2]
[ 7, 10,  3, 10,  3,  6,  3,  2]
[ 9,  6,  5,  2,  7,  6,  3,  2]
[ 3,  6,  1,  6,  3, 10,  5,  6]
[ 7, 10,  5,  4,  5,  2,  3,  6]
[ 5,  8,  3,  8,  7,  8,  9,  6]
[ 3,  4,  1,  6,  5,  6,  7,  4]
[(0, 0), (1, 3), (2, 7), (3, 6), (4, 4), (5, 5), (6, 2), (7, 1)]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]]
coût= 80
